### ISSUE TITLE
Style css not working

### ISSUE THREAD

**Issue by realmcc** [coffeebank/moonrise#14]

**Comment by coffeebank** [comment]
Hello, could you please clarify what you need help with?

- What type of Minecraft server are you using Moonrise for?
- How have you tried to set up Moonrise?
- Where did you run into the style css error?
- What were you trying to do?

Thank you

**Comment by coffeebank** [comment]
Please join [the Discord](https://coffeebank.github.io/discord) for support when you are ready.
